// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5587.robot;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public static int LEFT_FRONT_MOTOR = 0;
	public static int LEFT_REAR_MOTOR = 1;
	public static int RIGHT_FRONT_MOTOR = 2;
	public static int RIGHT_REAR_MOTOR = 3;
	
	//Shooting mechanism
	public static int LEFT_SHOOTER_WHEEL = 8;
	public static int RIGHT_SHOOTER_WHEEL = 9;
	public static int LOADING_SERVO = 6;
	public static int TOP = 2;
	public static int BOTTOM_LIMIT = 3;
	
    //Aiming mechanism
	public static int LIFT_MOTOR = 7;
	public static int ENCODER_A = 0;
	public static int ENCODER_B = 1;
	
	//Joysticks
	public static int DRIVER = 0;
	public static int CODRIVER = 1;
	
	//Buttons
	public static int FIRE = 1; //Begins sequence of actually shooting a boulder
	public static int PRIME = 4;
	public static int SWEEP_IN = 3; //Spins the wheels inward to collect a boulder
	public static int UP = 8;
	public static int DOWN = 7;
}
